spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: bankuser
    password: bankpass
  jpa:
    hibernate:
      ddl-auto: update   # or validate/create-drop for testing
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082
